/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projects */
        get: operations["projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan */
        post: operations["rescan_api_index_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__uid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{uid}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Children */
        get: operations["session_children_api_sessions__uid__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{uid}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Raw */
        get: operations["session_raw_api_sessions__uid__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{uid}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Session */
        get: operations["export_session_api_sessions__uid__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{uid}/resume-command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume Command */
        get: operations["resume_command_api_sessions__uid__resume_command_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/bind-workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind Workspace */
        post: operations["bind_workspace_api_actions_bind_workspace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actions/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal
         * @description Open the OS file manager at a source file. Confined to detected roots.
         */
        post: operations["reveal_api_actions_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Server-sent events: index progress and session updates.
         */
        get: operations["events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionResult */
        ActionResult: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string | null;
        };
        /** AppStatus */
        AppStatus: {
            /** Version */
            version: string;
            index: components["schemas"]["IndexStatus"];
            /** State Dir */
            state_dir: string;
            /** Provider Counts */
            provider_counts: {
                [key: string]: number;
            };
        };
        /** BindWorkspaceRequest */
        BindWorkspaceRequest: {
            /** Workspace Hash */
            workspace_hash: string;
            /** Path */
            path: string;
        };
        /** CompactionPart */
        CompactionPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "compaction";
            /** Text */
            text: string | null;
        };
        /** ErrorPart */
        ErrorPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Message */
            message: string;
        };
        /** FilePart */
        FilePart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            /** Path */
            path: string | null;
            /** Mime */
            mime: string | null;
            /** Size */
            size: number | null;
            /** Text */
            text: string | null;
            /** Data Url */
            data_url: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** IndexStatus */
        IndexStatus: {
            /**
             * Running
             * @default false
             */
            running: boolean;
            /**
             * Scanned
             * @default 0
             */
            scanned: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Indexed Sessions
             * @default 0
             */
            indexed_sessions: number;
            /** Last Error */
            last_error: string | null;
            /** Last Finished At */
            last_finished_at: string | null;
        };
        /**
         * Locator
         * @description Where a normalized record came from, for the raw inspector.
         */
        Locator: {
            /** Source */
            source: string;
            /** Line */
            line: number | null;
            /** Key */
            key: string | null;
        };
        /** Message */
        Message: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "tool";
            /** Created At */
            created_at: string | null;
            /** Parts */
            parts: (components["schemas"]["TextPart"] | components["schemas"]["ReasoningPart"] | components["schemas"]["ToolPart"] | components["schemas"]["FilePart"] | components["schemas"]["PatchPart"] | components["schemas"]["SnapshotPart"] | components["schemas"]["StepPart"] | components["schemas"]["TodoPart"] | components["schemas"]["SubtaskPart"] | components["schemas"]["CompactionPart"] | components["schemas"]["ErrorPart"] | components["schemas"]["UnknownPart"])[];
            tokens: components["schemas"]["TokenUsage"] | null;
            /** Cost */
            cost: number | null;
            /** Model */
            model: string | null;
            /** Error */
            error: string | null;
        };
        /** PatchFile */
        PatchFile: {
            /** Path */
            path: string;
            /** Status */
            status: string | null;
            /** Diff */
            diff: string | null;
            /** Additions */
            additions: number | null;
            /** Deletions */
            deletions: number | null;
        };
        /** PatchPart */
        PatchPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "patch";
            /** Files */
            files: components["schemas"]["PatchFile"][];
            /** Unified Diff */
            unified_diff: string | null;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Cwd */
            cwd: string | null;
            /** Name */
            name: string;
            /** Session Count */
            session_count: number;
            /** Providers */
            providers: ("codex" | "cursor-cli" | "cursor-ide" | "opencode")[];
            /** Updated At */
            updated_at: string | null;
        };
        /** ProviderStatus */
        ProviderStatus: {
            /**
             * Id
             * @enum {string}
             */
            id: "codex" | "cursor-cli" | "cursor-ide" | "opencode";
            /** Name */
            name: string;
            /** Detected */
            detected: boolean;
            /** Roots */
            roots: string[];
            /** Session Count */
            session_count: number | null;
            /** Error */
            error: string | null;
            /** Note */
            note: string | null;
        };
        /** ReasoningPart */
        ReasoningPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "reasoning";
            /** Text */
            text: string;
            /**
             * Encrypted
             * @default false
             */
            encrypted: boolean;
        };
        /**
         * ResumeCommand
         * @description A command the user can copy. The server never runs it.
         */
        ResumeCommand: {
            /** Command */
            command: string;
            /** Cwd */
            cwd: string | null;
            /** Note */
            note: string | null;
        };
        /** RevealRequest */
        RevealRequest: {
            /** Path */
            path: string;
        };
        /** SearchHit */
        SearchHit: {
            /** Uid */
            uid: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "codex" | "cursor-cli" | "cursor-ide" | "opencode";
            /** Title */
            title: string | null;
            /** Project */
            project: string | null;
            /** Role */
            role: ("user" | "assistant" | "system" | "tool") | null;
            /** Message Id */
            message_id: string | null;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /** Items */
            items: components["schemas"]["SearchHit"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Query
             * @default
             */
            query: string;
        };
        /** Session */
        Session: {
            summary: components["schemas"]["SessionSummary"];
            /** Messages */
            messages: components["schemas"]["Message"][];
            /** Warnings */
            warnings: components["schemas"]["Warning_"][];
            /** Notes */
            notes: string[];
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /** SessionPage */
        SessionPage: {
            /** Items */
            items: components["schemas"]["SessionSummary"][];
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * Limit
             * @default 50
             */
            limit: number;
        };
        /** SessionSummary */
        SessionSummary: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "codex" | "cursor-cli" | "cursor-ide" | "opencode";
            /** Id */
            id: string;
            /** Uid */
            uid: string;
            /** Title */
            title: string | null;
            /** Cwd */
            cwd: string | null;
            /** Project */
            project: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Message Count */
            message_count: number | null;
            /** Model */
            model: string | null;
            /** Git Branch */
            git_branch: string | null;
            /** Parent Uid */
            parent_uid: string | null;
            /**
             * Kind
             * @default main
             * @enum {string}
             */
            kind: "main" | "subagent";
            tokens: components["schemas"]["TokenUsage"] | null;
            /** Cost */
            cost: number | null;
            /** Source Path */
            source_path: string;
            /** Source Mtime */
            source_mtime: number | null;
            /** Source Size */
            source_size: number | null;
            /**
             * Parse Status
             * @default ok
             * @enum {string}
             */
            parse_status: "ok" | "partial" | "error";
        };
        /** SnapshotPart */
        SnapshotPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
            /** Ref */
            ref: string | null;
            /** Files Changed */
            files_changed: number | null;
        };
        /** Stats */
        Stats: {
            /**
             * Total Sessions
             * @default 0
             */
            total_sessions: number;
            /**
             * Total Messages
             * @default 0
             */
            total_messages: number;
            /**
             * Tokens Input
             * @default 0
             */
            tokens_input: number;
            /**
             * Tokens Output
             * @default 0
             */
            tokens_output: number;
            /**
             * Cost
             * @default 0
             */
            cost: number;
            /** By Provider */
            by_provider: components["schemas"]["StatsBucket"][];
            /** By Model */
            by_model: components["schemas"]["StatsBucket"][];
            /** By Day */
            by_day: components["schemas"]["StatsBucket"][];
        };
        /** StatsBucket */
        StatsBucket: {
            /** Key */
            key: string;
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
            /**
             * Messages
             * @default 0
             */
            messages: number;
            /**
             * Tokens Input
             * @default 0
             */
            tokens_input: number;
            /**
             * Tokens Output
             * @default 0
             */
            tokens_output: number;
            /**
             * Cost
             * @default 0
             */
            cost: number;
        };
        /** StepPart */
        StepPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "step";
            /**
             * Phase
             * @default finish
             * @enum {string}
             */
            phase: "start" | "finish";
            tokens: components["schemas"]["TokenUsage"] | null;
            /** Cost */
            cost: number | null;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** SubtaskPart */
        SubtaskPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "subtask";
            /** Session Uid */
            session_uid: string | null;
            /** Title */
            title: string | null;
            /** Agent */
            agent: string | null;
        };
        /** TextPart */
        TextPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** TodoItem */
        TodoItem: {
            /** Content */
            content: string;
            /** Status */
            status: string | null;
        };
        /** TodoPart */
        TodoPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "todo";
            /** Items */
            items: components["schemas"]["TodoItem"][];
        };
        /** TokenUsage */
        TokenUsage: {
            /** Input */
            input: number | null;
            /** Output */
            output: number | null;
            /** Cache Read */
            cache_read: number | null;
            /** Cache Write */
            cache_write: number | null;
            /** Reasoning */
            reasoning: number | null;
        };
        /** ToolPart */
        ToolPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "tool";
            /** Name */
            name: string;
            /** Call Id */
            call_id: string | null;
            /** Input */
            input: unknown | null;
            /** Output */
            output: string | null;
            /**
             * Status
             * @default completed
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "error";
            /** Error */
            error: string | null;
            /** Title */
            title: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            } | null;
        };
        /** UnknownPart */
        UnknownPart: {
            /** Id */
            id: string;
            locator: components["schemas"]["Locator"] | null;
            /** Raw */
            raw: unknown | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "unknown";
            /** Kind */
            kind: string;
            /** Data */
            data: unknown | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input: unknown;
            /** Context */
            ctx: Record<string, never>;
        };
        /**
         * Warning_
         * @description A non-fatal parsing problem. Surfaced in the UI, never raised.
         */
        Warning_: {
            /** Message */
            message: string;
            locator: components["schemas"]["Locator"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatus"];
                };
            };
        };
    };
    providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStatus"][];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                provider?: string[] | null;
                project?: string | null;
                q?: string | null;
                kind?: ("main" | "subagent") | null;
                since?: string | null;
                until?: string | null;
                sort?: "updated" | "created" | "messages" | "title";
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
        };
    };
    rescan_api_index_rescan_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_sessions__uid__get: {
        parameters: {
            query?: {
                raw?: boolean;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_children_api_sessions__uid__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_raw_api_sessions__uid__raw_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_session_api_sessions__uid__export_get: {
        parameters: {
            query?: {
                format?: "md" | "json";
                redact?: boolean;
            };
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_command_api_sessions__uid__resume_command_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_workspace_api_actions_bind_workspace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BindWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_api_actions_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
